/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4RNimhIRFzx
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableCell, TableRow, TableHead, TableBody, Table } from "@/components/ui/table"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Badge } from "@/components/ui/badge"

export function ClassStats() {
  return (
    
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="max-w-6xl w-full mx-auto grid gap-2">
          <h1 className="font-semibold text-3xl">Teacher's Dashboard</h1>
          <div className="flex items-center text-sm gap-2">
            <a className="font-medium" href="#" target="_blank">
              codeGuardian.com
            </a>
            <Separator className="h-5" orientation="vertical" />
            <div className="text-gray-500 flex items-center gap-2 dark:text-gray-400">
              <span className="inline-block w-2 h-2 bg-[#09CE6B] rounded-full animate-ping duration-[5000]" />
              32 users online
            </div>
          </div>
        </div>
        <div className="grid gap-6 md:grid-cols- xl:grid-cols-4 max-w-6xl w-full mx-auto">
          <Card>
            <CardHeader className="flex flex-row items-center border-b">
              <CardTitle>Students</CardTitle>
              <CardDescription className="ml-auto">Total</CardDescription>
            </CardHeader>
            <CardContent className="text-4xl font-bold">1,234</CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center border-b">
              <CardTitle>Assignments</CardTitle>
              <CardDescription className="ml-auto">Completed</CardDescription>
            </CardHeader>
            <CardContent className="text-4xl font-bold">5,678</CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center border-b">
              <CardTitle>Activity</CardTitle>
              <CardDescription className="ml-auto">Today</CardDescription>
            </CardHeader>
            <CardContent className="text-4xl font-bold">987</CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center border-b">
              <CardTitle>Integrity Alerts</CardTitle>
              <CardDescription className="ml-auto">Pending</CardDescription>
            </CardHeader>
            <CardContent className="text-4xl font-bold">23</CardContent>
          </Card>
        </div>
        <div className="grid gap-6 max-w-6xl w-full mx-auto">
          <Card>
            <CardHeader className="flex flex-row items-center border-b">
              <CardTitle>Code Timeline</CardTitle>
              <CardDescription className="ml-auto">History</CardDescription>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell className="text-xs">
                      <span className="text-sm">Time</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">User</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">File</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">Line</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">Operation</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">Content</span>
                    </TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  <TableRow>
                    <TableCell>10:00</TableCell>
                    <TableCell>alice</TableCell>
                    <TableCell>index.js</TableCell>
                    <TableCell>10</TableCell>
                    <TableCell>edit</TableCell>
                    <TableCell>console.log('hello');</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>10:05</TableCell>
                    <TableCell>bob</TableCell>
                    <TableCell>index.js</TableCell>
                    <TableCell>10</TableCell>
                    <TableCell>edit</TableCell>
                    <TableCell>console.log('cheating');</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>10:10</TableCell>
                    <TableCell>alice</TableCell>
                    <TableCell>index.js</TableCell>
                    <TableCell>10</TableCell>
                    <TableCell>edit</TableCell>
                    <TableCell>console.log('hello');</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center border-b">
              <CardTitle>Integrity Alerts</CardTitle>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button className="ml-auto" size="icon" variant="ghost">
                    <MoreHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>Refresh</DropdownMenuItem>
                  <DropdownMenuItem>Manage</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell className="text-xs">
                      <span className="text-sm">Time</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">Student</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">File</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">Line</span>
                    </TableCell>
                    <TableCell className="text-xs">
                      <span className="text-sm">Status</span>
                    </TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  <TableRow>
                    <TableCell>10:00</TableCell>
                    <TableCell>alice</TableCell>
                    <TableCell>index.js</TableCell>
                    <TableCell>10</TableCell>
                    <TableCell>
                      <Badge variant="error">Cheating</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>10:05</TableCell>
                    <TableCell>bob</TableCell>
                    <TableCell>index.js</TableCell>
                    <TableCell>10</TableCell>
                    <TableCell>
                      <Badge variant="success">Valid</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>10:10</TableCell>
                    <TableCell>alice</TableCell>
                    <TableCell>index.js</TableCell>
                    <TableCell>10</TableCell>
                    <TableCell>
                      <Badge variant="success">Valid</Badge>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </main>
  )
}


function FrameIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  )
}


function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  )
}
